# Generated by Django 2.0 on 2018-01-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name': 'Places', 'verbose_name_plural': 'Places'},
        ),
    ]
