# Generated by Django 2.0 on 2018-02-25 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
