# Generated by Django 2.0 on 2018-01-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='shop',
        ),
        migrations.AddField(
            model_name='goods',
            name='place',
            field=models.ManyToManyField(related_name='place', to='home.Places'),
        ),
    ]
